[workspace]

members = [
    "lcdemo",
    "str_demo",
    "graphics_demo",
    "double_ptr",
    "dfs_and_bfs",
    "cache",
    "arr_demo",
    "math_demo",
    "dp_demo",
    "list_demo",
    "matrix_demo",
    "send_point",
    "simple_demo",
    "tree_demo"
]
